export default {
  'en': {
    translation: {
      // Global definitions
      remote_advisor: 'Remote Advisor',
      // Workflow names
      op_workflow_name: 'OP workflow',
      remote_advisor_workflow_name: 'Remote Advisor workflow',
      // Form descriptions
      form_davivienda_raffle_entry_name: 'Raffle Entry',
      form_davivienda_signature_card_name: 'Individual Card',
      form_davivienda_credit_card_application_name: 'Credit Card Application',
      form_wintrust_raffle_entry_name: 'Raffle Entry',
      form_davivienda_individual_account_application_name: 'Individual Account Application',
      form_wintrust_customer_information_profile_name: 'Customer Information Form',
      form_banking_contact_info_name: 'Contact Info',
      form_remote_advisor_contact_info_name: 'Contact Info',
      form_op_raffle_entry_name: 'Raffle Entry',
      form_op_customer_onboarding_name: 'Customer onboarding',
      form_claro_raffle_entry_name: 'Raffle Entry',
      // Capture types
      capture_area_type_downward_facing_full: 'Full (mat)',
      capture_area_type_downward_facing_zoomed: 'Zoomed area (mat)',
      capture_area_type_downward_facing_letter: 'Letter',
      capture_area_type_downward_facing_id_card: 'ID card',
      capture_area_type_downward_facing_passport: 'Passport',
      capture_area_type_forward_facing_full: 'Full (webcam)',
      capture_area_type_forward_facing_face: 'Face',
      // Languages
      language_en_US: 'English (US)',
      language_es_CO: 'Spanish (Colombia)',
      language_ru: 'Russian (Russian Federation)',
      language_fi: 'Finnish',
      language_sv: 'Swedish',
      // Call queue page (/)
      call_queue_header: 'Call queue',
      there_are_no_calls_in_the_queue: 'There are no calls in the queue at the moment.',
      workflow_type: 'Workflow type',
      call_queue: 'Call queue',
      call_date_time_header: 'Call date/time',
      kiosk_id_header: 'Kiosk ID',
      client_type_header: 'Client type',
      version_format: 'Version: {{version}}',
      answer_call_button: 'Answer call',
      finished_calls: 'Finished calls',
      call_duration_header: 'Call duration',
      kiosk_language_header: 'Kiosk language',
      // Call page (/call)
      call_header: 'Call',
      capture_options: 'Capture options',
      perform_capture: 'Perform capture',
      capture_tab: 'Capture',
      share_tab: 'Share',
      external_website_tab: 'Web',
      landing_page_tab: 'No Share',
      end_call_button: 'End call',
      open_script_tooltip: 'Open script',
      script_sidebar_header: 'Script',
      end_call_modal_header: 'End call',
      end_call_modal_question: 'Are you sure you want to end this call?',
      end_call_modal_confirm: 'End call',
      end_call_modal_return: 'Return to call',
      signature_sidebar_header: 'Signature',
      signature_sidebar_toggle_text: 'Toggle signature pad',
      captures_sidebar_header: 'Captures',
      edit_form_button: 'Edit',
      send_form_button: 'Send',
      chrome_browser_required: 'Chrome browser is required for proper operation',
      highlight_area: 'Highlight area',
      zoom_and_pan: 'Zoom & pan video'
    },
  },
  'ru': {
    translation: {
      // Global definitions
      remote_advisor: 'Удаленный Cоветник',
      // Workflow names
      op_workflow_name: 'Рабочий процесс OP',
      // Form descriptions
      form_davivienda_raffle_entry_name: 'Лотерея',
      form_davivienda_signature_card_name: 'Индивидуальная карта',
      form_davivienda_credit_card_application_name: 'Заявление на получение кредитной карты',
      form_wintrust_raffle_entry_name: 'Лотерея',
      form_davivienda_individual_account_application_name: 'Индивидуальный аккаунт',
      form_wintrust_customer_information_profile_name: 'Форма информации о клиенте',
      form_op_raffle_entry_name: 'Лотерея',
      form_claro_raffle_entry_name: 'Лотерея',
      form_op_customer_onboarding_name: 'Регистрация клиента',
      // Capture types
      capture_area_type_downward_facing_full: 'Полный (коврик)',
      capture_area_type_downward_facing_zoomed: 'Увеличенная область (коврик)',
      capture_area_type_downward_facing_letter: 'Письмо',
      capture_area_type_downward_facing_id_card: 'Удостоверение личности',
      capture_area_type_downward_facing_passport: 'Паспорт',
      capture_area_type_forward_facing_full: 'Полный (веб-камера)',
      capture_area_type_forward_facing_face: 'Лицо',
      // Languages
      language_en_US: 'Английский (США)',
      language_es_CO: 'Испанский (Колумбия)',
      language_ru: 'Русский (Российская Федерация)',
      language_fi: 'финский',
      language_sv: 'шведский',
      // Call queue page (/)
      call_queue_header: 'Очередь звонков',
      there_are_no_calls_in_the_queue: 'В очереди нет звонков.',
      workflow_type: 'Тип рабочего процесса',
      call_queue: 'Очередь звонков',
      call_date_time_header: 'Дата / время звонка',
      kiosk_id_header: 'Киоск ID',
      client_type_header: 'Тип клиента',
      version_format: 'Версия: {{version}}',
      answer_call_button: 'Ответ на звонок',
      finished_calls: 'Завершенные звонки',
      call_duration_header: 'Длительность звонка',
      kiosk_language_header: 'Язык киоска',
      // Call page (/call)
      call_header: 'Вызов',
      capture_options: 'Варианты захвата',
      perform_capture: 'Выполнить захват',
      capture_tab: 'Захватить',
      external_website_tab: 'Web',
      share_tab: 'Поделиться',
      landing_page_tab: 'Нет обмена',
      end_call_button: 'Конец вызова',
      open_script_tooltip: 'Открытый скрипт',
      script_sidebar_header: 'скрипт',
      end_call_modal_header: 'Конец вызова',
      end_call_modal_question: 'Вы уверены, что хотите завершить этот звонок?',
      end_call_modal_confirm: 'Конец вызова',
      end_call_modal_return: 'Вернуться к звонку',
      signature_sidebar_header: 'Подпись',
      signature_sidebar_toggle_text: 'Переключить панель подписи',
      captures_sidebar_header: 'Захватывает',
      edit_form_button: 'редактировать',
      send_form_button: 'послать',
      chrome_browser_required: 'Браузер Chrome необходим для правильной работы',
      highlight_area: 'Выделить область',
      zoom_and_pan: 'Масштаб и панорамирование видео'
    },
  },
  'es-CO': {
    translation: {
      // Global definitions
      remote_advisor: 'Remote Advisor',
      // Workflow names
      op_workflow_name: 'Flujo de trabajo de OP',
      remote_advisor_workflow_name: 'Flujo de trabajo de Remote Advisor',
      // Form descriptions
      form_davivienda_raffle_entry_name: 'Boleto de Rifa',
      form_davivienda_signature_card_name: 'Solicitud de tarjeta individual',
      form_davivienda_credit_card_application_name: 'Solicitud de tarjeta de crédito',
      form_wintrust_raffle_entry_name: 'Boleto de Rifa',
      form_davivienda_individual_account_application_name: 'Solicitud de Vinculación Persona Natural',
      form_banking_contact_info_name: 'Información del contacto',
      form_remote_advisor_contact_info_name: 'Información del contacto',
      form_op_raffle_entry_name: 'Boleto de Rifa',
      form_op_customer_onboarding_name: 'Incorporación de clientes',
      form_claro_raffle_entry_name: 'Boleto de Rifa',
      // Capture types
      capture_area_type_downward_facing_full: 'Completo (mat)',
      capture_area_type_downward_facing_zoomed: 'Área ampliada (tapete)',
      capture_area_type_downward_facing_letter: 'Hoja',
      capture_area_type_downward_facing_id_card: 'Tarjeta de identificación',
      capture_area_type_downward_facing_passport: 'Pasaporte',
      capture_area_type_forward_facing_full: 'Completo (webcam)',
      capture_area_type_forward_facing_face: 'Cara',
      // Languages
      language_en_US: 'Inglés (EEUU)',
      language_es_CO: 'Español (Colombia)',
      language_ru: 'Ruso (Federación de Rusia)',
      language_fi: 'Finlandés',
      language_sv: 'Sueca',
      // Call queue page (/)
      call_queue_header: 'Cola de llamadas',
      there_are_no_calls_in_the_queue: 'No hay llamadas en la cola en este momento.',
      workflow_type: 'Tipo de flujo de trabajo',
      call_queue: 'Cola de llamadas',
      call_date_time_header: 'Fecha/hora de llamada',
      kiosk_id_header: 'Identificación del kiosk',
      client_type_header: 'Tipo de cliente',
      version_format: 'Versión: {{version}}',
      answer_call_button: 'Responder la llamada',
      finished_calls: 'Llamadas terminadas',
      call_duration_header: 'Duración de la llamada',
      kiosk_language_header: 'Idioma del kiosk',
      // Call page (/call)
      call_header: 'Llamada',
      capture_options: 'Opciones de captura',
      perform_capture: 'Realizar captura',
      capture_tab: 'Capturar',
      external_website_tab: 'Web',
      share_tab: 'Compartir',
      landing_page_tab: 'No compartir',
      end_call_button: 'Finalizar llamada',
      open_script_tooltip: 'Script abierto',
      script_sidebar_header: 'Script',
      end_call_modal_header: 'Finalizar llamada',
      end_call_modal_question: '¿Estás seguro de que quieres finalizar esta llamada?',
      end_call_modal_confirm: 'Finalizar llamada',
      end_call_modal_return: 'Volver a llamar',
      signature_sidebar_header: 'Firma',
      signature_sidebar_toggle_text: 'Palanca pad de signatura',
      captures_sidebar_header: 'Captura',
      edit_form_button: 'Editar',
      send_form_button: 'Enviar',
      chrome_browser_required: 'Se requiere el navegador Chrome para un correcto funcionamiento',
      highlight_area: 'Área resaltada',
      zoom_and_pan: 'Zoom y panorámica de video'
    },
  },
};