export default {
  'en': {
    translation: {
      'connecting': 'Connecting ...',
      'entering_call_queue': 'Entering call queue ...',
      'place_doc_here': 'Place Document Here',
      'remote_advisor': 'Remote Advisor',
      'welcome_start_here': 'Start here!',
      'welcome_contact_an_agent': 'Contact your agent',
      'clear_signature': 'Clear signature',
      'submit_signature': 'Submit signature',
      'cancel_call': 'Cancel call',
      'look_up': 'Please look up for image capture',
      'op_smart_advisor': 'OP Smart Advisor',
    },
  },
  'es-CO': {
    translation: {
      'connecting': 'Conectando ...',
      'entering_call_queue': '... Lo estamos comunicando con un operador ...',
      'place_doc_here': 'Colocar el documento aquí',
      'remote_advisor': 'Asesor Remoto',
      'welcome_contact_an_agent': 'Pulse para comunicarse con un operador',
      'clear_signature': 'Clara firma',
      'submit_signature': 'Presentar firma',
      'cancel_call': 'Cancelar llamada',
      'look_up': 'Por favor, busque la captura de imágenes',
      'op_smart_advisor': 'OP Asesor Inteligente',
    },
  },
  'ru': {
    translation: {
      'connecting': 'Cоединительный ...',
      'entering_call_queue': 'Вход в очередь вызовов ...',
      'place_doc_here': 'Разместить документ здесь',
      'remote_advisor': 'Удаленный советник',
      'welcome_start_here': 'Начни здесь!',
      'welcome_contact_an_agent': 'Связаться с агентом',
      'clear_signature': 'Очистить подпись',
      'submit_signature': 'Отправить подпись',
      'cancel_call': 'Отменить звонок',
      'look_up': 'Пожалуйста, посмотрите изображение захвата',
      'op_smart_advisor': 'OP Удаленный Cоветник',
    },
  },
  'fi': {
    translation: {
      'connecting': 'Yhdistetään ...',
      'entering_call_queue': 'Olet jonossa ...',
      'place_doc_here': 'Aseta asiakirja tähän',
      'remote_advisor': 'Palveluasema',
      'welcome_start_here': 'Aloita tästä!',
      'welcome_contact_an_agent': 'Ota yhteyttä asiakasneuvojaasi',
      'clear_signature': 'Tyhjennä allekirjoitus',
      'submit_signature': 'Lähetä allekirjoitus',
      'cancel_call': 'Peruuta puhelu',
      'look_up': 'Ole hyvä ja katso eteenpäin',
      'op_smart_advisor': 'OP Palveluasema',
    },
  },
  'sv': {
    translation: {
      'connecting': 'Anslutning ...',
      'entering_call_queue': 'Anger anropskö ...',
      'place_doc_here': 'Placera dokument här',
      'remote_advisor': 'OP Service Terminal',
      'welcome_start_here': 'Börja här!',
      'welcome_contact_an_agent': 'Kontakt din bankrådgivare',
      'clear_signature': 'Tydlig signatur',
      'submit_signature': 'Skicka signatur',
      'cancel_call': 'Avbryt samtal',
      'look_up': 'Snälla se framåt',
      'op_smart_advisor': 'OP Service Terminal',
    },
  },
};